---
    - name: Nginx/install repo
      become: true
      ansible.builtin.yum:
        name:
          - epel-release
        state: present
      tags: Lighthouse

    - name: Nginx/install nginx
      become: true
      ansible.builtin.yum:
        name:
          - nginx
        state: present
      tags: Lighthouse
      
    - name: Nginx/create config nginx
      become: true
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify: Start_nginx
      tags: Lighthouse
      
    - name: Lighhouse/install git
      become: true
      ansible.builtin.yum:
        name: git
        state: present
      tags: Lighthouse
      
    - name: Lighhouse/download distrib
      become: true
      ansible.builtin.git:
        repo: "{{ lighthouse_vcs }}"
        dest: "{{ lighthouse_location_dir }}"
        version: master
      tags: Lighthouse

    - name: Lighhouse/config
      become: true
      ansible.builtin.template:
        src: lighthouse.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: "0644"
      notify: Reload_nginx
      tags: Lighthouse
