---
- name: Start_nginx
  become: true
  ansible.builtin.command: nginx
  register: my_output
  changed_when: my_output.rc != 0
- name: Reload_nginx
  become: true
  ansible.builtin.command: nginx -s reload
  register: my_output
  changed_when: my_output.rc != 0
